// Playwright Configuration — Auto-generated by UVT (URAE v1)
// Framework: Laravel | Project type: SSR
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests/generated',
  timeout: 45000,
  use: {
    baseURL: 'http://localhost:3000',
    headless: true,
    screenshot: 'only-on-failure'
  },
  reporter: [['html', { outputFolder: '.uvt/playwright-report' }]]
});
